### ISSUE TITLE
Commands don’t save meta information

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#545] opened 2019-09-10 09:16 UTC
As discussed in #542, it seems as if commands do not save their meta information. The behavior exhibited seems similar to when documenting modules was impossible.

Cheers

**Comment by eriksvedang** [comment] 2020-04-30 13:05
This works now? @hellerve

**Comment by hellerve** [comment] 2020-04-30 14:12
It doesn’t seem to:

```
> (info Dynamic.String.concat)
concat : Dynamic
Defined at line 0, column 0 in 'dummy-file'
> (doc Dynamic.String.concat "concats a string dynamically")
> (info Dynamic.String.concat)
concat : Dynamic
Defined at line 0, column 0 in 'dummy-file'
```

**Comment by eriksvedang** [comment] 2020-05-03 17:56
Huh, it works for me on `bit-width`:

```clojure
鲤 :i bit-width 
bit-width : Dynamic Defined at line 0, column 0 in 'dummy-file'
鲤 (doc bit-width "stuff")
鲤 :i bit-width
bit-width : a
Defined at line 0, column 0 in 'dummy-file'
Documentation: stuff
```

So maybe it's something with commands inside modules.

**Comment by hellerve** [comment] 2020-05-03 18:31
Maybe, but also the type changed in your example (from `Dynamic` to`a`), which leads me to believe that that’s a doc stub we’re seeing.

**Comment by hellerve** [comment] 2020-05-03 19:37
But it does look like this works as of current master, insofar as docstubs are created correctly.

**Comment by eriksvedang** [comment] 2020-05-03 20:22
Oh, right... totally missed that! Needs more investigation then, hopefully it's not that hard to fix since it works for other kinds of definitions.

**Comment by eriksvedang** [comment] 2020-05-05 14:37
I think this should be fixed in `master` now..!

**Comment by eriksvedang** [comment] 2020-05-05 14:41
For posterity, the bug was caused by two things:
1. The commands that were added to the starting env had their Path XObj:s set to `SymPath [] name`, they are now qualified like this `SymPath ["Dynamic"] name`
2. When looking up symbols in `primitiveMetaSet`, we need to do an additional attempt where `Dynamic` is prepended to the path or else you won't find the symbol, in which case a stub will be created instead.

**Comment by hellerve** [comment] 2020-05-05 16:02
Oh, fun! Thanks for the explanation :)

**Closed** 2020-05-06 09:48 UTC
