### ISSUE TITLE
Can't compile using Vector

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#516] opened 2019-07-06 16:52 UTC
If I try to compile:

```
(load "Vector.carp")
(defn main []
  0)
```

`Maybe__bool` ends up being undefined (only `Maybe__int` is defined).

```
[nix-shell:~/src/Carp/Carp]$ cabal new-run carp -- -b /tmp/test.carp
Up to date
./out/main.c:699:25: error: unknown type name 'Maybe__bool'
void Maybe_delete__bool(Maybe__bool p);
                        ^
./out/main.c:2015:25: error: unknown type name 'Maybe__bool'
void Maybe_delete__bool(Maybe__bool p) {
                        ^
./out/main.c:2016:16: error: use of undeclared identifier 'Maybe__bool_Just_tag'
  if(p._tag == Maybe__bool_Just_tag) {
               ^
./out/main.c:2019:21: error: use of undeclared identifier 'Maybe__bool_Nothing_tag'
  else if(p._tag == Maybe__bool_Nothing_tag) {
                    ^
4 errors generated.
carp: callCommand: clang -fPIC -lm -g ./out/main.c -o "./out/Untitled"  -I.//core/   (exit 1): failed

[nix-shell:~/src/Carp/Carp]$ 
```

**Comment by jacereda** [comment] 2019-07-06 16:54
Oops, looks like it has to do with some local changes I have made in the `Vector` module. I'll try to isolate the problem.

**Comment by jacereda** [comment] 2019-07-06 17:45
I reduced it to:

```
(defn angle-between [a b]
    (Maybe.Just (zero)))
(defn anti-parallel? [a b]
    (Maybe.apply (angle-between a b) (fn [x] (= x pi))))

(defn main [] 0)
```

That should yield the same errors.

**Comment by hellerve** [comment] 2019-09-08 18:36
It seems like the specialized type 'Maybe__bool' is not being emitted. Do you know from the top of your head what the conditions for a type being emitted are, @eriksvedang?

**Comment by hellerve** [comment] 2019-09-09 07:44
I think I know what the issue is. It seems as if `fn` forms aren’t actually annotated like
`defn`s are. I’m not quite positive about this part, but I’m guessing that leads to the
types that the `fn` depends on not being put in the type environment. @eriksvedang does
this sound like it makes sense?

**Comment by eriksvedang** [comment] 2019-09-09 12:32
Yeah sounds about right. Should I fix it?

**Comment by hellerve** [comment] 2019-09-09 12:41
That’d be great. I’d love to see how that’d work, but I’m not sure I could fix it myself.

**Comment by eriksvedang** [comment] 2019-09-09 16:19
OK, I’ll give it a go then!

**Comment by eriksvedang** [comment] 2019-09-10 09:41
This is fixed in master now.

**Closed by eriksvedang** 2019-09-10 09:41 UTC
Labels: bug
