### ISSUE TITLE
Given-away value in while condition, not in if condition

### ISSUE THREAD

**Issue by jkleiser** [carp-lang/Carp#441] opened 2019-05-13 09:23 UTC
I cannot understand why I get an error message on the `(set! str (Maybe.Nothing))` expression in the `while` condition (line 9), while the exact same expression is accepted in the `if` condition (line 4):
```
(defn main []
  (let [str (Maybe.Just @"dummy")]
    (do
      (if (do (set! str (Maybe.Nothing))
                  (Maybe.just? &str))
        (IO.println &(Maybe.from str @""))
        (IO.println "got Nothing"))
      
      (while (do (set! str (Maybe.Nothing))
                  (Maybe.just? &str))
        (IO.println &(Maybe.from str @"")))
      (IO.println "done"))))
```
The error message I get is this:
```
You’re using a given-away value `str` at line 9, column 24 in '/Volumes/P3/CarpStuff/hello3.carp'.

You’ll have to copy the value using `@`.
```

**Comment by hellerve** [comment] 2019-05-13 10:43
This happens because `set!` takes ownership of the `str` variable in the `if` and in the `while`. This is bad enough, but then Carp also can’t guarantee that the body of the `while` isn’t executed multiple times and, again, ownership of `str` is taken again multiple times. It makes total sense from a lifetime POV, but it’s neither ergonomic nor satisfying.

This is part of the “fun” you have when dealing with a lifetime system that isn’t quite expressive enough yet, I fear.

**Comment by jkleiser** [comment] 2019-05-13 11:02
If I am to replace the `(Maybe.Nothing)` in the `while` loop with a call to a function that reads a file line-by-line, returning each line in a Maybe, and a Maybe.Nothing if EOF, what would be a nice way to write that? (I have given the `read-line` function a couple of times at https://gitter.im/carp-lang/Carp.)

**Comment by hellerve** [comment] 2019-05-13 11:18
Looking at your function, I was actually completely off. The problem does not actually occur in the call to `read-line`—I keep forgetting some special rules around `set!` that @eriksvedang can probably explain.

The problem is the line `(IO.println &(Maybe.from line @""))`, because it takes ownership over `line`. There are two ways around this: you can either copy the value, rewriting the line to `(IO.println &(Maybe.from @&line @""))`, introducing some inefficiencies. Alternatively, you can rewrite the `main` function, getting rid of `line` entirely:

```
(defn main []
  (let [f (IO.fopen "short.txt" "rb")]
    (do
      (while true
        (match (read-line f)
          (Maybe.Just v) (IO.println &v)
          (Maybe.Nothing) (break)))
      (IO.fclose f))))
```

Sorry for leading you down the wrong track at first!

**Comment by jkleiser** [comment] 2019-05-13 11:28
That works like a dream! Thanks.

**Comment by hellerve** [comment] 2019-05-13 18:06
Can we close this issue, then?

**Closed** 2019-05-13 20:24 UTC
