### ISSUE TITLE
pattern matching too greedy

### ISSUE THREAD

**Issue by guberathome** [carp-lang/Carp#1264] opened 2021-06-30 14:36 UTC
Assume we want to match markdown references like ```[description](URl)```.
Note there is no character between both parts (description and URl).

The current implementation delivers false matches, when the parts are separated by whitespace:
```
Welcome to Carp 0.5.1
This is free software with ABSOLUTELY NO WARRANTY.
Evaluate (help) for more information.
> (Pattern.match-all-groups  #"\[(.-)\]\((.-)\)"  "icke [dette] (xyz) [kieke]\n\t(...) [mal](oochen,) fleesch un beene")
[[@"dette] (xyz) [kieke]
        (...) [mal" @"oochen,"]]
>
```

The correct results would be:
```
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import re
>>> pat = re.compile("\[(.*?)\]\((.*?)\)")
>>> re.findall( pat, "icke [dette] (xyz) [kieke]\n\t(...) [mal](oochen,) fleesch un beene" )
[('mal', 'oochen,')]
```

**Comment by guberathome** [comment] 2021-06-30 19:44
Since carp_pattern.h is derived from lua, let's check if they have the same problem in the newest version:
```
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
> cap1, cap2 = string.match( "icke [dette] (xyz) [kieke]\n\t(...) [mal](oochen,) fleesch un beene", "%[(.-)%]%((.-)%)" )
> cap1
dette] (xyz) [kieke]
	(
	...) [mal
> cap2
oochen,
```
So the problem persists, updating to a newer lua version is not a viable path.

**Comment by hellerve** [comment] 2021-06-30 20:30
I don’t think this is a bug, since the matches are valid in a non-backtracking pattern system (note that this is not the same as a regex, which does backtrack, which is required to satisfy “as few characters matched as possible” with the preceding matches in mind).

Now, a simple way to fix this would be to make the requirement “do not match brackets” explicit, like so:

```clojure
> (Pattern.match-all-groups  #"ups  #"\[([^\[\]]-)\]\((.-)\)"  "icke [dette] (xyz) [kieke]\n\t(...) [mal](oochen,) fleesch un beene")
[[@"mal" @"oochen,"]]
```

Which is, in my eyes, a better constraint anyway, since “match all characters”, or `.`, isn’t actually expressing the intent correctly.

**Comment by guberathome** [comment] 2021-06-30 21:34
Agreed, this behaviour is a limitation that is build into the matching algorithm, regardless of whether you call it a "bug" or a "constraint".

So my preferred way forward would be:
1. change the concrete usage in PR #1256 as suggested by @hellerve 
2. include this example in the documentation to document the limitation and provide a work-around.

**Comment by hellerve** [comment] 2021-06-30 21:43
Right, I wasn’t suggesting that it’s not undesirable behavior, I was just unsure whether to classify it as a bug!

I’m good with both of your points. Maybe a broader explanation of the lack of backtracking and what that means might be in order? I can write something up if you’d like, unless you feel that task is calling you—you’ve been so active lately!

**Comment by guberathome** [comment] 2021-06-30 22:09
I'd be happy for you to take the documentation part here in order to concentrate on the PR.

**Comment by hellerve** [comment] 2021-07-05 13:25
I’ll close this for now as "works as intended", since #1268 is merged.

**Closed by hellerve** 2021-07-05 13:25 UTC
Labels: bug, core-libs
