### ISSUE TITLE
Calling `main` at the repl doesn't work

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#556] opened 2019-09-13 08:39 UTC
Since calling a function at the repl temporarily overwrites the `main` function, calling the actual `main` function doesn't work. This should be pretty simple to work around.

**Comment by hellerve** [comment] 2020-04-18 10:25
Oh, it looks like #713 is actually a duplicate of this! My fix in #716 should work to close this as well!

**Closed** 2020-04-30 12:36 UTC
Labels: bug, help wanted
