### ISSUE TITLE
Want testing functions for checking errors occur

### ISSUE THREAD

**Issue by mkfifo** [carp-lang/Carp#235] opened 2018-05-20 03:40 UTC
It would be nice to have some assert-fails which runs an expression and expects it to fail (e.g. it will run an assert and exit with non zero)

A use case for this would be for testing aset! where we want to check that it deals with bounds behaviour correctly

For string-set! I would like to be able to write

```
(assert-fails
    &(let-do [str @"abcd"]
        (string-set! &str 4 \q)) ;; this should fail and throw an assert
    "string-set! correctly detects out of bounds writes"
)
````

**Comment by hellerve** [comment] 2018-05-20 04:44
The problem is that C `assert`s abort the process on failure, which means we cannot really do anything with them. Maybe if we provided our own definition of `assert` that overrides the one provided by the system we could hack something up?

**Comment by mkfifo** [comment] 2018-05-20 06:53
The libcheck testing library runs each test in a new process so that it can test for various forms of exit (assert, exit, segfault, ...).

If we only want to test assert, we could try swapping it out, although it might be cleaner to use CARP_assert and leave the stdlib assert untouched.

**Comment by hellerve** [comment] 2018-05-20 15:57
Right. I might be able to work on this sometime this week; it would be nice if we could tackle concurrency at some point anyway.

**Comment by hellerve** [comment] 2018-05-23 11:54
I created a function inside `Test` that looks like this:

```
(load "Test.carp")

(use Test)

(defn die []
  (System.exit 1))

(defn main []
  (with-test test
    (assert-fails test
                  1
                  die
                  "can exit with return code 1"
    )
    (print-test-results test)))
```

So if you wanted to test for a failed `assert`, you’d have to check for `SIGABRT`. Would that be to your liking?

**Comment by hellerve** [comment] 2018-05-23 11:57
Ecch, actually this is a signal, and as such has nothing to do with the exit code. We will have to catch the signals as well...

**Comment by eriksvedang** [comment] 2018-05-23 19:20
I think it's OK to close it. There are probably a hole bunch of other things that will require porting to Windows, so this case isn't that special.

**Closed by eriksvedang** 2018-05-23 19:20 UTC

**Comment by mkfifo** [comment] 2018-05-24 00:16
@hellerve thank you!
