### ISSUE TITLE
More Detailed C Interop Documentation

### ISSUE THREAD

**Issue by sdilts** [carp-lang/Carp#534] opened 2019-08-07 23:12 UTC
One thing I feel is missing from the documentation is a more detailed guide on C interoperability. There are several vital functions like `add-pkg`, `add-cflag`, and `add-lib` not mentioned in the language guide that are present in the SDL bindings included with Carp. In addition, there seem to be some incompatibilities like array types and C unions that are probably worth mentioning. Are these already documented somewhere?

Here are a couple of questions I'd like to see answered by the documentation, which I am having a hard time answering:

- [ ] Do Carp arrays require any unpacking before they can be passed to C functions? If so, is it done automatically?
- [ ] Is it possible to register structures that contain arrays? If so, how do I access items in them? For example:
   ``` C
   struct example1 {
        int array[5];
   };
   struct example2 {
        int *array;
   };
   ```
- [ ] Do structs and enums need to be `typedef`ed in order to be generated properly? All of the examples I have looked through seem to imply yes.
- [ ] How are enums handled?
- [ ] How are structs without a name handled? e.g.
  ``` C
  struct unnamed_inner {
     struct {
          int a;
          int b;
     } inner;
  };
  ```

I'm in the process of writing more detailed documentation in the form of a guide, and feel it would be incomplete without these details. Are there any more points that should be addressed in any updated documentation?

**Comment by hellerve** [comment] 2019-08-08 09:55
Thank you for looking into this, especially since this is one of the more gnarly bits of any programming language!

I’ll try to go through those questions one by one:
1. Carp arrays are structs (they know about their length and capacity as well), and as such either can be passed as those structs or a pointer to the data can be obtained by calling `Array.raw`. Any sort of guarantees that Carp can give are dropped then, though (this is generally true when manipulating things in C, I might add).
2. There are no statically allocated arrays, but they are planned to be added in the future (see also #507). As for C arrays, you’ll have to use `(Ptr <type>)` to declare them, since they are not the same as Carp arrays (see 1).
3. There are multiple ways in which you can interface with a C struct: you can ignore it and generate a type variable—though that will probably end badly—, you can use an opaque `deftype`, i.e. `(deftype MyStruct)`, which will register the type, but you won’t be able to do anything with it—none of the functions that are usually generated, like accessors and stringification, will be generated etc.—, or you can `deftype` the whole thing in Carp again, and every function will be generated.
4. AFAIK we don’t really handle C enums. You can register the enum values one by one as values, but not as one unit. We have our own enum system—sumtypes without members—, that is more typesafe, for better or worse.
5. AFAIK not at all. I guess we’re deferring this until it becomes a real problem—which is how we handle most of the development behind Carp, by design, to keep things minimal.

I hope that helps a little bit!

**Comment by Kampouse** [comment] 2020-11-05 14:32
Another thing that is not really clear is do you  handle (void*)  inside of the C interop

**Comment by hellerve** [comment] 2020-11-05 14:57
This is a super interesting question, since `void*` is a bit of a manual generic type. You can resolve it in a few different ways in Carp: using `Unsafe.coerce` to cast another pointer, using a fake pointer in the template if you know you always want a certain type (for instance `(Ptr Byte)`), or using a generic type in Carp and hoping for the best.

But I agree, these options and their drawbacks should be discussed more deeply!

**Comment by Kampouse** [comment] 2020-11-05 15:16
Reprensenting *void as type for  register-type would be ( Ptr byte) right? 
Am sorry to ask these question ;c trying to bind a physic engine to carp 
I previously use @ would allow me to compile would not know if i was following the right type for the library

**Comment by hellerve** [comment] 2020-11-05 15:19
You could use `(Ptr Byte)` if you want to pass it bytes. The most accurate type would be `(Ptr ())`, but then you’d definitely need `Unsafe.coerce` to cast types.

Context: `()` is the "empty" or "unit" type, which is what `void` is in C. So `(Ptr ())` translates to `void*`.

**Comment by Kampouse** [comment] 2020-11-05 15:23
When trying to use  (Ptr ()) compiler would complain it cant use () at x 🤔

**Comment by hellerve** [comment] 2020-11-05 15:34
Oh, that’s a bug in `register-type`! I’ll look into it!

**Comment by eriksvedang** [comment] 2020-11-23 22:00
Perhaps this works now with @scolsen:s fixes to () ?

**Comment by hellerve** [comment] 2020-11-24 10:09
I think this should have worked with #948 already!

**Comment by hellerve** [comment] 2020-11-24 10:09
(But that’s not what this issue is mainly about, sorry for closing)

**Comment by eriksvedang** [comment] 2020-11-24 13:08
I think the issue was kinda hijacked :) If the bug is solved we can close this, since the C interop document is done too.

**Closed** 2020-11-30 09:19 UTC
Labels: bug
