### ISSUE TITLE
Loading game.carp and reloading all project files causes "too many functions found" errors

### ISSUE THREAD

**Issue by pluckyporcupine** [carp-lang/Carp#698] opened 2020-03-17 20:38 UTC
When I load `game.carp` and type `:r`, it throws "too many functions found" errors for both `copy` and `delete`.

Output:
```
> (load "D:\Code\GitHub\Carp\examples\game.carp")
> :r
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'copy' functions found with type (Fn [(Ref Order q)] Order), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
Too many 'delete' functions found with type (Fn [Order] ()), can't figure out dependencies.
```

**Comment by hellerve** [comment] 2020-03-17 20:44
I suppose we should special-case `reload` in that all reloading should not verify duplicate functions and instead override them. This could potentially be unsafe, though (if we override functions that are defined somewhere else).

What do you think @eriksvedang?

**Comment by eriksvedang** [comment] 2020-03-18 09:25
This used to not be an issue, something must have changed. I’ll look into it. Thanks for the bug report!

**Comment by eriksvedang** [comment] 2020-03-19 08:11
Seems like this is the problematic commit:
https://github.com/carp-lang/Carp/commit/edee6d9dc94ff1304ba9ab458ae9578313d28b39

**Comment by scolsen** [comment] 2020-03-20 11:47
> Seems like this is the problematic commit:
> 
> https://github.com/carp-lang/Carp/commit/edee6d9dc94ff1304ba9ab458ae9578313d28b39

whoops, thats on me—looks like it probably has to do with multiple functions having the signature [Order] -> ()) though I’m not precisely sure what’s wrong with the way the module is defined—somehow it results in multiple definitions.

**Comment by scolsen** [comment] 2020-03-20 11:50
Actually, It think the same reload bug may occur whenever one reloads the Binary module in the repl—there’s something wrong w/ the way the module is defined, but I’m not sure what.

**Comment by hellerve** [comment] 2020-03-20 12:48
I think I found a minimal reproducible example for this bug, and it seems to be unrelated to `Binary`. Here’s the reproduction steps:

```clojure
; the type needs to be defined in a module
(defmodule X
  ; it needs to have documentation
  (doc Y "")
  (deftype Y A B)

  ; and it needs to be used
  (defn x [] (Y.A))
)
```

Now how the heck all of these features interrelate to create unsound code I don’t quite know.

**Comment by scolsen** [comment] 2020-03-20 23:49
#701 temporarily fixes the Binary module so that it at least doesn't cause this error to arise...but it's something we should resolve. @hellerve's diagnosis is correct, this issue crops up whenever you:

1. Define a type in a module
2. Set the doc meta for the type by calling `(doc)`
3. Use the type.
4. Load the file defining the type a second time in the Repl (call reload)

Here are some notes that might be interesting:

- Types defined directly in modules defined in the Repl circumvent this issue. e.g. running the following directly in the repl:
```
(defmodule Foo (doc Bar "foobar") (deftype Bar Baz) (defn f [] (Bar.Baz)))
:r
```
results in no issues (presumably b/c :r is a no-op in this case?). Loading the same exact code from a file will cause `:r` calls to throw the errors mentioned earlier (too many deletes).

- Dropping the call to `doc` weirdly resolves the issue entirely.

- The same issue occurs when defining structs as well, not just sumtypes.

**Comment by eriksvedang** [comment] 2020-03-23 09:06
OK, that's just super weird. Thanks for investigating it so thoroughly.

**Comment by eriksvedang** [comment] 2020-05-06 12:27
This is fixed in `master` now.

**Comment by eriksvedang** [comment] 2020-05-06 12:28
@scolsen So if you want to undo your temprorary fixes for this, please do!

**Closed** 2020-05-06 12:27 UTC
Labels: bug
