### ISSUE TITLE
Stack-allocated strings/arrays

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#507] opened 2019-06-18 22:11 UTC
Are there plans to support stack-allocated strings/arrays?

**Comment by eriksvedang** [comment] 2019-06-19 05:30
Yes. Strings already are stack allocated but the plan is to have a way to create stack allocated arrays as well. Exactly what limitations they will have isn’t clear yet though.

**Comment by jacereda** [comment] 2019-06-19 06:14
By stack-allocated strings I mean the equivalent of:

```
struct spath {
  char path[MAXPATH];
};

spath wd;
get_working_directory(&wd);
```

Unless I'm missing something, there's no way to do that currently.

**Comment by hellerve** [comment] 2019-06-20 13:27
There is no way to have non-literal stack-allocated strings ATM, so you are correct. Those should definitely exist, though, and I’d hope for the underlying mechanism to be similar to that of stack-allocated arrays.

**Comment by eriksvedang** [comment] 2019-06-20 17:53
Oh, right – that's correct. And both features should probably be developed in tandem since they are so related.

**Comment by chrisosaurus** [comment] 2019-07-09 08:28
AFAIk we currently rely on the C stack. What happens if the requested object is too large for the stack?

**Comment by jacereda** [comment] 2019-07-09 14:09
The same thing that happens in C, you get a nice crash and then you can choose between:

- Allocating a bigger stack.
- Reducing the stack-allocated buffer sizes.
- Switch to heap-allocated buffers.

**Comment by bjorn3** [comment] 2019-07-09 14:39
> you get a nice crash

[stack clash](https://askubuntu.com/questions/927188/what-is-stack-clash-and-what-can-i-do-about-it/927190#927190)?

**Comment by jacereda** [comment] 2019-07-09 14:52
> Or [stack clash](https://askubuntu.com/questions/927188/what-is-stack-clash-and-what-can-i-do-about-it/927190#927190)?

I'd consider that an OS bug.

**Comment by eriksvedang** [comment] 2019-07-11 20:47
I think @jacereda:s reasoning here is sound. The goal is to have stack allocated arrays in the language before version 1.0, whenever that is. For people who care about this, it's an important enough feature.

**Comment by chrisosaurus** [comment] 2019-07-22 11:09
> The same thing that happens in C, you get a nice crash [...]

Exceeding the stack length is undefined behaviour in C, and stack length depends on runtime.
Stack length issues often don't crash tidily and instead can lead to hard to find/reproduce bugs.

This could mean Carp programs would no longer be portable.

To get around this we could try add logic to impose our own conservatively portable maximum stack size.

Most of the popular compilers support flags to enable either static or dynamic checking of stack sizes, we'd likely want to impose some limit and guarantee that either us or the underlying C compiler can detect it statically.

**Comment by jacereda** [comment] 2019-10-02 22:13
I'm considering writing a libclang-based bindings generator, but one of the major problems in handling structs with fixed-size arrays. What's the plan to address this? Can I help somehow?

**Comment by eriksvedang** [comment] 2019-10-03 08:19
My ideal solution is to add a type, something like `(FixArray Int a)`, that carries with it the length of the array. To make that not lead to problems in the general case is pretty hard though, and I don't think it's wise to implement before lifetimes are working (they are required to make it safe, and also the changes to type inference will collide with the lifetime ones). I spent a lot of time on lifetimes in the summer but they are not ready to be merged yet, unfortunately. So I think it's hard to do anything with this for the moment. Sorry for being the bottleneck here... I'll try to get lifetimes finished as quickly as I can.

If you want to experiment with just adding that type `(FixArray Int a)` and making it work *just* for `register-type` (so external types only), that could be a much smaller and isolated undertaking perhaps (based on gut feeling). But if you want to try, I'm all up for it!

**Comment by eriksvedang** [comment] 2020-04-30 12:40
There's a version of this in `master` now. It does not carry its length as part of the type though, and can't be used as a member of a struct yet, so there's definitely some work left on it.

**Closed** 2020-05-05 14:54 UTC
Labels: enhancement
