### ISSUE TITLE
Should have system to run tests over compiler and repl

### ISSUE THREAD

**Issue by chrisosaurus** [carp-lang/Carp#257] opened 2018-06-23 04:14 UTC
Issues like #255 should be able to be caught by a system which runs the full test suite over the compiler and interpreter

**Comment by mkfifo** [comment] 2018-06-23 04:17
This is caused by using using Haskell `/` instread of `quot` for integers
in src/Commands.hs commandDiv

**Comment by mkfifo** [comment] 2018-06-24 01:37
My concern was mosty for simple things like math being different between them, we should have a way to catch that.

It might mean that a subset of the tests run for the interpreter, maybe only the tests for the core modules which should work across both.

**Comment by eriksvedang** [comment] 2019-05-10 09:12
I think writing a separate test suite for the interpreter will be cleaner, so I'll close this for now.

**Closed by eriksvedang** 2019-05-10 09:12 UTC
