### ISSUE TITLE
Maybe test failure

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#494] opened 2019-06-13 18:27 UTC
I get the following output for the maybe.carp test:

```
Test 'nothing? works on Nothing' passed
Test 'nothing? works on Just' passed
Test 'just? works on Just' passed
Test 'just? works on Nothing' passed
Test 'from works on Just' passed
Test 'from works on Nothing' passed
Test 'unsafe-from works on Just' passed
Test 'apply works on Just' passed
Test 'apply works on Nothing' passed
Test 'or-zero works on Just' passed
Test 'or-zero works on Nothing' passed
Test 'to-result works on Just' passed
Test 'to-result works on Nothing' passed
Test 'ptr works on Just' failed:
	Expected value: '1', actual value: '0'
Test 'ptr works on Nothing' passed
Test 'from-ptr works on Ptr/Just' passed
Test 'from-ptr works on NULL/Nothing' passed
Results:
	|=================|
	Passed: 16	Failed: 1
[RUNTIME ERROR] '"./out/Untitled"' exited with return value 1.
```

**Comment by jacereda** [comment] 2019-06-13 18:27
On macOS, if that matters.

**Comment by jacereda** [comment] 2019-06-13 18:37
I think the problem resides here:

```
int* Maybe_ptr__int(Maybe__int a) {
    int* _15;
    if(a._tag == Maybe__int_Nothing_tag) {
        Maybe__int _5_temp = a;
        _15 = NULL;
    }
    else if(a._tag == Maybe__int_Just_tag) {
        Maybe__int _5_temp = a;
        int x = _5_temp.Just.member0;
        _15 = &x;
    }
    else {
      // This will not be needed with static exhaustiveness checking in 'match' expressions:
      fprintf(stderr, "Unhandled case in 'match' expression at line 58, column 5 in '/Volumes/Data/carp/Carp/core/Maybe.carp'\n");
      exit(1);
    }
    return _15;
}

```

Note how it's taking the address of the out-of-scope variable `x`.

**Comment by hellerve** [comment] 2019-06-13 18:53
I can’t reproduce this error; I’m also not sure `x` is out of scope, since it’s a member of `a` being passed back into the scope where `a` is defined. Am I missing something?

I’m also on OS X btw.

**Comment by jacereda** [comment] 2019-06-13 18:55
I'm probably using a newer clang, since I'm using nixpkgs.
`_15` contains the address of the stack-allocated variable `x`, so it's returning the address of a stack variable. That's bad.

**Comment by hellerve** [comment] 2019-06-13 18:55
What version of Clang are you using?

**Comment by jacereda** [comment] 2019-06-13 18:56
```
clang --version
clang version 7.1.0 (tags/RELEASE_710/final)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /nix/store/kxfkny9867qzndaskvvbk14h3i1p5hpz-clang-7.1.0/bin

```

**Comment by hellerve** [comment] 2019-06-13 18:56
For reference, this is mine:

```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
```

**Comment by hellerve** [comment] 2019-06-13 18:57
Okay, will try to reproduce.

**Comment by jacereda** [comment] 2019-06-13 18:58
I think the problem is related to `tempVarToAvoidClash` in the `Match` handling.

**Comment by hellerve** [comment] 2019-06-13 19:18
Alright, so I reproduced it (after isntalling Nix and the whole thing) and looked at it. The sad part is that the C is actually “correct”. What’s wrong is actually the implementation in Carp:

```clojure
  (defn ptr [a]
    (match a
      (Nothing) NULL
      (Just x) (address x)))
```

What `address` does is _take the address of whatever is being passed, bypassing the ownership system_. So I brought this upon us. I thought `address` was smarter than it actually is (it just puts a `&` before whatever comes after, basically).

I don’t know whether the semantics of `address` should be fixed, since it’s really, really unsafe, but also potentially necessary to interface with C, or whether the Carp code should be fixed. Either of both has to be done.

Thank you for your bug report, and sorry for not seeing why the emitted C code was bad (obvious in hindsight).

**Comment by eriksvedang** [comment] 2019-06-13 19:40
Good find @jacereda! And I think your analysis is spot on @hellerve, not sure what the best action is. But the current implementation of `ptr` seems like it has to go, at least...

**Closed** 2019-06-17 18:23 UTC
