### ISSUE TITLE
Local variables can't share names with commands/macros/functions in the dynamic context.

### ISSUE THREAD

**Issue by sdilts** [carp-lang/Carp#659] opened 2020-01-30 00:54 UTC
When trying to use a name for a local variable that has the same name a command, macro, or dynamic function in the dynamic context, Carp doesn't overshadow that global variable or provide warnings. Changing the variable name to something else fixes the problem.

For example, you cannot use `c` as a variable name, as it is a function.
```  clojure
(let [c (car (list 1 2 3))]
     (list c))

= > invalid args to 'c' command
```
Issue #555 suggests we wrap the result in `(quote ...)` while using the REPL, which results in:
```  clojure
(quote (let [c (car (list 1 2 3))]
     (list c)))

= > ((command c))
```
If we use a variable name that is not a function, everything works fine:
```  clojure
(quote (let [foo (car 0 (list 1 2 3))]
     (list foo)))
=> (1)
```

This is the case for code run in the REPL and while compiling a file. If you place the following code into a file, then load it and look at `test-val`'s value, you will see that the same thing occurs.
``` clojure
(defdynamic test-val (let [c (car (list 1 2 3))]
                        c))
```
You can try this with `car`, `e`, `nthcdr`, `nthcar`, etc. and a similar result occurs.

**Comment by sdilts** [comment] 2020-01-30 00:58
Possibly related to #597

**Comment by hellerve** [comment] 2020-01-30 01:01
I suspect this is also the root cause of the weird issues we’re seeing in #460.

As discussed in #555, we’ll have to rewrite the evaluator ina  more principled manner; hopefully that will fix a bunch of these issues all at once.

**Comment by eriksvedang** [comment] 2020-01-30 13:38
Nice find @sdilts! But yes, what @hellerve said. I'll leave this open though, as a reminder.

**Comment by eriksvedang** [comment] 2020-04-30 12:21
Is this fixed now because of #695 being merged?

**Comment by eriksvedang** [comment] 2020-04-30 12:30
OK, it's not a giant problem but I'll keep the issue open then.

**Comment by scolsen** [comment] 2021-05-22 16:11
As @hellerve stated, this ultimately comes down to our lookup orders. 

Ideally, preferring local environments before the Dynamic environment wouldn't cause any problems and could fix this issue. I'll give it a shot.

**Comment by scolsen** [comment] 2021-05-22 21:04
I have a fix for this...but oddly it seems to make `postwalk`, and co. unacceptable performance wise. It doesn't seem to have any other effect, though.

**Comment by scolsen** [comment] 2021-05-22 21:20
In particular, it makes the performance of walk-replace prohibitve and breaks the behavior of postwalk. Prewalk is strangely unaffected as are all other functions and test thus far—so the solution doesn’t account for an edge

**Closed** 2021-05-24 06:58 UTC
Labels: bug, difficult

**Comment by hellerve** [comment] 2021-05-24 09:56
> In particular, it makes the performance of walk-replace prohibitve and breaks the behavior of postwalk. Prewalk is strangely unaffected as are all other functions and test thus far—so the solution doesn’t account for an edge

Is this still the case with #1214?
